export class Consts {
    static readonly Events = {
        LOG_REQUESTED: 'LOG_REQUESTED',
        ALERT_REQUESTED: 'ALERT_REQUESTED',
        PROMOTION_CODE_COLLECTED: 'PROMOTION_CODE_COLLECTED',
        PROMOTION_CODE_CONSUMED: 'PROMOTION_CODE_CONSUMED',
    } as const;
}
